[master]
k8s-master ansible_host=51.107.69.36

[worker]
k8s-worker ansible_host=20.203.144.155

[all:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'